Init Led Service files
intel-aero/meta-intel-aero-base pull request #5
Opened 2017-06-07 05:58 UTC by Rjasuja

Control LEDs on boot up to indicate the boot up cycle.

2017-06-07 06:02 UTC, avinash-palleti commented
@lucasdemarchi we have verified this on Aero. LED is turning Green once boot process is completed.

2017-06-07 06:15 UTC, lucasdemarchi requested changes

2017-06-07 06:15 UTC, lucasdemarchi commented on recipes-support/notify-led/files/LICENSE
> +Apache License
Why are we adding licenses everywhere? meta layer already has a license that's applied to everything inside.

2017-06-07 08:30 UTC, Rjasuja commented
Deleted License File and update recipe file

2017-06-22 00:13 UTC, lucasdemarchi commented
I'd prefer something that monitors the progress property as I mentioned before. But this is not critical for now so I'm merging it so we can move on.

2017-06-22 00:13 UTC, merged